/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GeneralTools_FilePreallocator */

#ifndef _Included_GeneralTools_FilePreallocator
#define _Included_GeneralTools_FilePreallocator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GeneralTools_FilePreallocator
 * Method:    _preallocate
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_GeneralTools_FilePreallocator__1preallocate
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
