/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ReceiveTools_UdpSocket */

#ifndef _Included_ReceiveTools_UdpSocket
#define _Included_ReceiveTools_UdpSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ReceiveTools_UdpSocket
 * Method:    openUdpSocket
 * Signature: (Ljava/lang/String;II)LReceiveTools/Pointer;
 */
JNIEXPORT jobject JNICALL Java_ReceiveTools_UdpSocket_openUdpSocket
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     ReceiveTools_UdpSocket
 * Method:    getUdpReceivedPacket
 * Signature: (LReceiveTools/Pointer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ReceiveTools_UdpSocket_getUdpReceivedPacket
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ReceiveTools_UdpSocket
 * Method:    closeUdpSocket
 * Signature: (LReceiveTools/Pointer;)V
 */
JNIEXPORT void JNICALL Java_ReceiveTools_UdpSocket_closeUdpSocket
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ReceiveTools_UdpSocket
 * Method:    dropAllUdpReceivedPackets
 * Signature: (LReceiveTools/Pointer;)V
 */
JNIEXPORT void JNICALL Java_ReceiveTools_UdpSocket_dropAllUdpReceivedPackets
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
