/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ReceiveTools_UdpSocket_Pointer */

#ifndef _Included_ReceiveTools_UdpSocket_Pointer
#define _Included_ReceiveTools_UdpSocket_Pointer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
